-- IDS (ID's)
CREATE TABLE IDS  (
  TABLE_NAME varchar(60) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
-- 테이블 설명 추가
CREATE COMMENT ON IDS IS 'IDS';
-- 컬럼 설명 추가
CREATE COMMENT ON COLUMN IDS.TABLE_NAME IS '테이블명';
CREATE COMMENT ON COLUMN IDS.NEXT_ID IS '다음 ID';

-- LET_TC_CMMN_CL_CODE (공통분류코드)
CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(180) ,
  CL_CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTCCMMNCLCODE IS '공통분류코드'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE IS '분류코드'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE_NM IS '분류코드명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE_DC IS '분류코드설명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_CODE (공통코드)
CREATE TABLE LETTCCMMNCODE (
  CODE_ID varchar(18) NOT NULL,
  CODE_ID_NM varchar(180) ,
  CODE_ID_DC varchar(600) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNCODE_PK PRIMARY KEY (CODE_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTCCMMNCODE IS '공통코드';
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID IS '코드ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID_NM IS '코드ID명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID_DC IS '코드ID설명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CL_CODE IS '분류코드'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_DETAI_LCODE (공통상세코드)
CREATE TABLE LETTCCMMNDETAILCODE (
  CODE_ID varchar(18) NOT NULL,
  CODE varchar(45) NOT NULL,
  CODE_NM varchar(180) ,
  CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE)
) ;

-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTCCMMNDETAILCODE IS '공통상세코드'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_ID IS '코드ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE IS '코드'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_NM IS '코드명'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_DC IS '코드설명'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ORGNZT_INFO (조직정보)
CREATE TABLE LETTNORGNZTINFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar(60) NOT NULL,
  ORGNZT_DC varchar(300) ,
  CONSTRAINT LETTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
) ;

-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNORGNZTINFO IS '조직정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_ID IS '조직ID'; 
CREATE COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_NM IS '조직명'; 
CREATE COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_DC IS '조직설명'; 

-- LET_TN_AUTHOR_GROUP_INFO (권한그룹정보)
CREATE TABLE LETTNAUTHORGROUPINFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar(180) NOT NULL,
  GROUP_CREAT_DE char(60) NOT NULL,
  GROUP_DC varchar(300) ,
  CONSTRAINT LETTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
) ;

-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNAUTHORGROUPINFO IS '권한그룹정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_NM IS '그룹명'; 
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_CREAT_DE IS '그룹생성일'; 
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_DC IS '그룹설명';

-- LET_TN_AUTHOR_INFO (권한정보)
CREATE TABLE LETTNAUTHORINFO (
  AUTHOR_CODE varchar(90) DEFAULT '' NOT NULL,
  AUTHOR_NM varchar(180) NOT NULL,
  AUTHOR_DC varchar(600) ,
  AUTHOR_CREAT_DE char(60) NOT NULL,
  CONSTRAINT LETTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNAUTHORINFO IS '권한정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_CODE IS '권한코드'; 
CREATE COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_NM IS '권한명'; 
CREATE COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_DC IS '권한설명'; 
CREATE COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_CREAT_DE IS '권한생성일'; 

-- LET_TN_ROLES_HIERARCHY (롤 계층구조)
CREATE TABLE LETTNROLES_HIERARCHY (
  PARNTS_ROLE varchar(90) NOT NULL,
  CHLDRN_ROLE varchar(90) NOT NULL,
  CONSTRAINT LETTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNROLES_HIERARCHY IS '롤 계층구조'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNROLES_HIERARCHY.PARNTS_ROLE IS '부모롤'; 
CREATE COMMENT ON COLUMN LETTNROLES_HIERARCHY.CHLDRN_ROLE IS '자식롤'; 

-- LET_TN_ROLE_INFO (롤정렬)
CREATE TABLE LETTNROLEINFO (
  ROLE_CODE varchar(150) DEFAULT '' NOT NULL,
  ROLE_NM varchar(180) NOT NULL,
  ROLE_PTTRN varchar(900) ,
  ROLE_DC varchar(600) ,
  ROLE_TY varchar(240) ,
  ROLE_SORT varchar(30) ,
  ROLE_CREAT_DE char(60) NOT NULL,
  CONSTRAINT LETTNROLEINFO_PK PRIMARY KEY (ROLE_CODE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNROLEINFO IS '롤정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNROLEINFO.ROLE_CODE IS '롤코드'; 
CREATE COMMENT ON COLUMN LETTNROLEINFO.ROLE_NM IS '롤명'; 
CREATE COMMENT ON COLUMN LETTNROLEINFO.ROLE_PTTRN IS '롤패턴'; 
CREATE COMMENT ON COLUMN LETTNROLEINFO.ROLE_DC IS '롤설명'; 
CREATE COMMENT ON COLUMN LETTNROLEINFO.ROLE_TY IS '롤유형'; 
CREATE COMMENT ON COLUMN LETTNROLEINFO.ROLE_SORT IS '롤정렬'; 
CREATE COMMENT ON COLUMN LETTNROLEINFO.ROLE_CREAT_DE IS '롤생성일'; 

-- LET_TN_AUTHOR_ROLE_RELATE (권한롤관계)
CREATE TABLE LETTNAUTHORROLERELATE (
  AUTHOR_CODE varchar(90) NOT NULL,
  ROLE_CODE varchar(150) NOT NULL,
  CREAT_DT DATETIME ,
  CONSTRAINT LETTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNAUTHORROLERELATE IS '권한롤관계'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNAUTHORROLERELATE.AUTHOR_CODE IS '권한코드'; 
CREATE COMMENT ON COLUMN LETTNAUTHORROLERELATE.ROLE_CODE IS '롤코드'; 
CREATE COMMENT ON COLUMN LETTNAUTHORROLERELATE.CREAT_DT IS '생성일시'; 

-- LET_TN_EMPLYR_INFO (업무사용자정보)
CREATE TABLE LETTNEMPLYRINFO (
  EMPLYR_ID varchar(60) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar(180) NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  EMPL_NO varchar(60) ,
  IHIDNUM varchar(39) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) ,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) ,
  ZIP varchar(18) ,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) ,
  EMAIL_ADRES varchar(150) ,
  OFCPS_NM varchar(180) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(60) ,
  SBSCRB_DE DATETIME ,
  CONSTRAINT LETTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNEMPLYRINFO IS '업무사용자정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMPLYR_ID IS '업무사용자ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.ORGNZT_ID IS '조직ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.USER_NM IS '사용자명'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD IS '비밀번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMPL_NO IS '사원번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.IHIDNUM IS '주민등록번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.SEXDSTN_CODE IS '성별코드'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.BRTHDY IS '생일'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.FXNUM IS '팩스번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_ADRES IS '주택주소'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD_HINT IS '비밀번호힌트'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD_CNSR IS '비밀번호정답'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_END_TELNO IS '주택끝전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.AREA_NO IS '지역번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.DETAIL_ADRES IS '상세주소'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.OFFM_TELNO IS '사무실전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.MBTLNUM IS '이동전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMAIL_ADRES IS '이메일주소'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.OFCPS_NM IS '직위명'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PSTINST_CODE IS '소속기관코드'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.ESNTL_ID IS '고유ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.CRTFC_DN_VALUE IS '인증DN값'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.SBSCRB_DE IS '가입일자'; 

-- LET_TN_EMPLYR_SCRTY_ESTBS (사용자보안설정)
CREATE TABLE LETTNEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(60) NOT NULL,
  MBER_TY_CODE varchar(45) ,
  AUTHOR_CODE varchar(90) NOT NULL
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNEMPLYRSCRTYESTBS IS '사용자보안설정'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNEMPLYRSCRTYESTBS.SCRTY_DTRMN_TRGET_ID IS '보안설정대상ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRSCRTYESTBS.MBER_TY_CODE IS '회원유형코드'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRSCRTYESTBS.AUTHOR_CODE IS '권한코드'; 

-- LET_TN_TMPLAT_INFO (템플릿정보)
CREATE TABLE LETTNTMPLATINFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM varchar(765) ,
  TMPLAT_COURS varchar(6000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNTMPLATINFO IS '템플릿정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_ID IS '템플릿ID'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_NM IS '템플릿명'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_COURS IS '템플릿경로'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_SE_CODE IS '템플릿구분코드'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
CREATE COMMENT ON COLUMN LETTNTMPLATINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_BBS_MASTER (게시판마스터)
CREATE TABLE LETTNBBSMASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(765) NOT NULL,
  BBS_INTRCN varchar(7200) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNBBSMASTER_PK PRIMARY KEY (BBS_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBSMASTER IS '게시판마스터'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_NM IS '게시판명'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_INTRCN IS '게시판소개'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_TY_CODE IS '게시판유형코드'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.REPLY_POSBL_AT IS '답장가능여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.FILE_ATCH_POSBL_AT IS '파일첨부가능여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.ATCH_POSBL_FILE_NUMBER IS '첨부가능파일숫자'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.ATCH_POSBL_FILE_SIZE IS '첨부가능파일사이즈'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.TMPLAT_ID IS '템플릿ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.LAST_UPDUSR_ID IS '최종수정자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_BBS_USE (게시판활용)
CREATE TABLE LETTNBBSUSE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBSUSE IS '게시판활용'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBSUSE.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.TRGET_ID IS '대상ID'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.REGIST_SE_CODE IS '등록구분코드'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_BBS (게시판)
CREATE TABLE LETTNBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) ,
  NTT_SJ varchar(6000) ,
  NTT_CN STRING,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO numeric(10,0) ,
  ANSWER_LC numeric(11) ,
  SORT_ORDR numeric(8,0) ,
  RDCNT numeric(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar(60) ,
  NTCR_NM varchar(60) ,
  PASSWORD varchar(600) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBS_PK PRIMARY KEY (NTT_ID,BBS_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBS IS '게시판'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBS.NTT_ID IS '게시물ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTT_NO IS '게시물번호'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTT_SJ IS '게시물제목'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTT_CN IS '게시물내용'; 
CREATE COMMENT ON COLUMN LETTNBBS.ANSWER_AT IS '댓글여부'; 
CREATE COMMENT ON COLUMN LETTNBBS.PARNTSCTT_NO IS '부모글번호'; 
CREATE COMMENT ON COLUMN LETTNBBS.ANSWER_LC IS '댓글위치'; 
CREATE COMMENT ON COLUMN LETTNBBS.SORT_ORDR IS '정렬순서'; 
CREATE COMMENT ON COLUMN LETTNBBS.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTNBBS.RDCNT IS '조회수'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCE_BGNDE IS '게시시작일'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCE_ENDDE IS '게시종료일'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCR_ID IS '게시자ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCR_NM IS '게시자명'; 
CREATE COMMENT ON COLUMN LETTNBBS.PASSWORD IS '비밀번호'; 
CREATE COMMENT ON COLUMN LETTNBBS.ATCH_FILE_ID IS '첨부파일ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBS.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTNBBS.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_ZIP (우편번호)
CREATE TABLE LETTCZIP (
  ZIP varchar(18) NOT NULL,
  SN numeric(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar(60) ,
  SIGNGU_NM varchar(60) ,
  EMD_NM varchar(180) ,
  LI_BULD_NM varchar(180) ,
  LNBR_DONG_HO varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCZIP_PK PRIMARY KEY (ZIP,SN)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTCZIP IS '우편번호'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTCZIP.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTCZIP.SN IS '일련번호'; 
CREATE COMMENT ON COLUMN LETTCZIP.CTPRVN_NM IS '시도명'; 
CREATE COMMENT ON COLUMN LETTCZIP.SIGNGU_NM IS '시군구명'; 
CREATE COMMENT ON COLUMN LETTCZIP.EMD_NM IS '읍면동명'; 
CREATE COMMENT ON COLUMN LETTCZIP.LI_BULD_NM IS '리건물명'; 
CREATE COMMENT ON COLUMN LETTCZIP.LNBR_DONG_HO IS '번지동호'; 
CREATE COMMENT ON COLUMN LETTCZIP.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTCZIP.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTCZIP.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTCZIP.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TH_EMPLYR_INFO_CHANGE_DTLS (업무사용자정보변경내역)
CREATE TABLE LETTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID varchar(60) NOT NULL,
  CHANGE_DE char(20) DEFAULT '' NOT NULL,
  ORGNZT_ID char(20) ,
  GROUP_ID char(20) ,
  EMPL_NO varchar(60) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) NOT NULL,
  ZIP varchar(18) NOT NULL,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) ,
  EMAIL_ADRES varchar(150) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) ,
  CONSTRAINT LETTHEMPLYRCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTHEMPLYRINFOCHANGEDTLS IS '업무사용자정보변경내역'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMPLYR_ID IS '업무사용자ID'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.CHANGE_DE IS '변경일'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.ORGNZT_ID IS '조직ID'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMPL_NO IS '사원번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.SEXDSTN_CODE IS '성별코드'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.BRTHDY IS '생일'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.FXNUM IS '팩스번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.HOUSE_ADRES IS '주택주소'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.HOUSE_END_TELNO IS '주택끝전화번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.AREA_NO IS '지역번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.DETAIL_ADRES IS '상세주소'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.OFFM_TELNO IS '사무실전화번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.MBTLNUM IS '이동전화번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMAIL_ADRES IS '이메일주소'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.PSTINST_CODE IS '소속기관코드'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
CREATE COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.ESNTL_ID IS '고유ID'; 

-- LET_TN_BBS_MASTER_OPTN (게시판마스터옵션)
CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATETIME DEFAULT SYSDATETIME NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBSMASTEROPTN IS '게시판마스터옵션'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.ANSWER_AT IS '댓글여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.STSFDG_AT IS '만족도여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ENTRPRS_MBER (기업회원)
CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(60) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar(30) ,
  JURIRNO varchar(39) ,
  CMPNY_NM varchar(180) NOT NULL,
  CXFC varchar(150) ,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  ENTRPRS_MIDDLE_TELNO varchar(12) ,
  FXNUM varchar(60) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar(150) ,
  APPLCNT_IHIDNUM varchar(39) ,
  SBSCRB_DE DATETIME ,
  ENTRPRS_MBER_STTUS varchar(45) ,
  ENTRPRS_MBER_PASSWORD varchar(600) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(300) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(300) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar(300) ,
  ENTRPRS_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  APPLCNT_EMAIL_ADRES varchar(150) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNENTRPRSMBER IS '기업회원'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_ID IS '기업회원ID'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_SE_CODE IS '기업구분코드'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.BIZRNO IS '사업자등록번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.JURIRNO IS '법인등록번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.CMPNY_NM IS '회사명'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.CXFC IS '대표이사'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ADRES IS '주소'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MIDDLE_TELNO IS '기업중간전화번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.FXNUM IS '팩스번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.INDUTY_CODE IS '업종코드'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_NM IS '신청인명'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_IHIDNUM IS '신청인주민등록번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.SBSCRB_DE IS '가입일자'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_STTUS IS '기업회원상태'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD IS '기업회원비밀번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_HINT IS '기업회원비밀번호힌트'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_CNSR IS '기업회원비밀번호정답'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.DETAIL_ADRES IS '상세주소'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_END_TELNO IS '기업끝전화번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.AREA_NO IS '지역번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_EMAIL_ADRES IS '신청자이메일주소'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_FILE (파일속성)
CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATETIME NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT LETTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNFILE IS '파일속성'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNFILE.ATCH_FILE_ID IS '첨부파일ID'; 
CREATE COMMENT ON COLUMN LETTNFILE.CREAT_DT IS '생성일시'; 
CREATE COMMENT ON COLUMN LETTNFILE.USE_AT IS '사용여부'; 

-- LET_TN_FILE_DETAIL (파일상세정보)
CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(6000) NOT NULL,
  STRE_FILE_NM varchar(765) NOT NULL,
  ORIGNL_FILE_NM varchar(765) ,
  FILE_EXTSN varchar(60) NOT NULL,
  FILE_CN STRING,
  FILE_SIZE numeric(8,0) ,
  CONSTRAINT LETTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNFILEDETAIL IS '파일상세정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.ATCH_FILE_ID IS '첨부파일ID'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_SN IS '파일순번'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_STRE_COURS IS '파일저장경로'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.STRE_FILE_NM IS '저장파일명'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.ORIGNL_FILE_NM IS '원파일명'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_EXTSN IS '파일확장자'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_CN IS '파일내용'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_SIZE IS '파일크기'; 

-- LET_TN_GNRL_MBER (일반회원)
CREATE TABLE LETTNGNRLMBER (
  MBER_ID varchar(60) DEFAULT '' NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  PASSWORD_HINT varchar(300) ,
  PASSWORD_CNSR varchar(300) ,
  IHIDNUM varchar(39) ,
  MBER_NM varchar(150) NOT NULL,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  AREA_NO varchar(12) ,
  MBER_STTUS varchar(45) ,
  DETAIL_ADRES varchar(300) ,
  END_TELNO varchar(12) ,
  MBTLNUM varchar(60) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar(60) ,
  MBER_EMAIL_ADRES varchar(150) ,
  MIDDLE_TELNO varchar(12) ,
  SBSCRB_DE DATETIME ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNGNRLMBER_PK PRIMARY KEY (MBER_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNGNRLMBER IS '일반회원'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_ID IS '회원ID'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD IS '비밀번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD_HINT IS '비밀번호힌트'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD_CNSR IS '비밀번호정답'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.IHIDNUM IS '주민등록번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_NM IS '회원명'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.ADRES IS '주소'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.AREA_NO IS '지역번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_STTUS IS '회원상태'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.DETAIL_ADRES IS '상세주소'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.END_TELNO IS '끝전화번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBTLNUM IS '이동전화번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_FXNUM IS '회원팩스번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_EMAIL_ADRES IS '회원이메일주소'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MIDDLE_TELNO IS '중간전화번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.SBSCRB_DE IS '가입일자'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.SEXDSTN_CODE IS '성별코드'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_LOGIN_LOG (접속로그)
CREATE TABLE LETTNLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(60) ,
  CONECT_IP varchar(69) ,
  CONECT_MTHD char(4) ,
  ERROR_OCCRRNC_AT char(1) ,
  ERROR_CODE char(3) ,
  CREAT_DT DATETIME ,
  CONSTRAINT LETTNLOGINLOG_PK PRIMARY KEY (LOG_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNLOGINLOG IS '접속로그'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNLOGINLOG.LOG_ID IS '로그ID'; 
CREATE COMMENT ON COLUMN LETTNLOGINLOG.CONECT_ID IS '접속ID'; 
CREATE COMMENT ON COLUMN LETTNLOGINLOG.CONECT_IP IS '접속IP'; 
CREATE COMMENT ON COLUMN LETTNLOGINLOG.CONECT_MTHD IS '접속방식'; 
CREATE COMMENT ON COLUMN LETTNLOGINLOG.ERROR_OCCRRNC_AT IS '오류발생여부'; 
CREATE COMMENT ON COLUMN LETTNLOGINLOG.ERROR_CODE IS '오류코드'; 
CREATE COMMENT ON COLUMN LETTNLOGINLOG.CREAT_DT IS '생성일시'; 

-- LET_TN_LOGIN_POLICY (로그인정책)
CREATE TABLE LETTNLOGINPOLICY (
  EMPLYR_ID varchar(60) DEFAULT '' NOT NULL,
  IP_INFO varchar(69) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMTT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNLOGINPOLICY IS '로그인정책'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.EMPLYR_ID IS '업무사용자ID'; 
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.IP_INFO IS 'IP정보'; 
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.DPLCT_PERM_AT IS '중복허용여부'; 
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.LMTT_AT IS '제한여부'; 
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.LAST_UPDUSR_ID IS '최종수정자ID'; 
CREATE COMMENT ON COLUMN LETTNLOGINPOLICY.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_PROGRM_LIST (프로그램목록)
CREATE TABLE LETTNPROGRMLIST (
  PROGRM_FILE_NM varchar(180) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar(300) NOT NULL,
  PROGRM_KOREAN_NM varchar(180) ,
  PROGRM_DC varchar(600) ,
  URL varchar(300) NOT NULL,
  CONSTRAINT LETTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNPROGRMLIST IS '프로그램목록'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_FILE_NM IS '프로그램파일명'; 
CREATE COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_STRE_PATH IS '프로그램저장경로'; 
CREATE COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_KOREAN_NM IS '프로그램한글명'; 
CREATE COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_DC IS '프로그램설명'; 
CREATE COMMENT ON COLUMN LETTNPROGRMLIST.URL IS 'URL'; 

-- LET_TN_MENU_INFO (메뉴정보)
CREATE TABLE LETTNMENUINFO (
  MENU_NM varchar(180) NOT NULL,
  PROGRM_FILE_NM varchar(180) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0) ,
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC varchar(750) ,
  RELATE_IMAGE_PATH varchar(300) ,
  RELATE_IMAGE_NM varchar(180) ,
  CONSTRAINT LETTNMENUINFO_PK PRIMARY KEY (MENU_NO)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNMENUINFO IS '메뉴정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNMENUINFO.MENU_NO IS '메뉴번호'; 
CREATE COMMENT ON COLUMN LETTNMENUINFO.UPPER_MENU_NO IS '상위메뉴번호'; 
CREATE COMMENT ON COLUMN LETTNMENUINFO.MENU_NM IS '메뉴명'; 
CREATE COMMENT ON COLUMN LETTNMENUINFO.PROGRM_FILE_NM IS '프로그램파일명'; 
CREATE COMMENT ON COLUMN LETTNMENUINFO.MENU_ORDR IS '메뉴순서'; 
CREATE COMMENT ON COLUMN LETTNMENUINFO.MENU_DC IS '메뉴설명'; 
CREATE COMMENT ON COLUMN LETTNMENUINFO.RELATE_IMAGE_PATH IS '관계이미지경로'; 
CREATE COMMENT ON COLUMN LETTNMENUINFO.RELATE_IMAGE_NM IS '관계이미지명'; 

-- LET_TN_MENU_CREAT_DTLS (메뉴생성내역)
CREATE TABLE LETTNMENUCREATDTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE varchar(90) NOT NULL,
  MAPNG_CREAT_ID varchar(90) ,
  CONSTRAINT LETTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNMENUCREATDTLS IS '메뉴생성내역'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNMENUCREATDTLS.MENU_NO IS '메뉴번호'; 
CREATE COMMENT ON COLUMN LETTNMENUCREATDTLS.AUTHOR_CODE IS '권한코드'; 
CREATE COMMENT ON COLUMN LETTNMENUCREATDTLS.MAPNG_CREAT_ID IS '매핑생성ID'; 

-- LET_TN_USER_ABSNCE (사용자부재)
CREATE TABLE LETTNUSERABSNCE (
  EMPLYR_ID varchar(60) DEFAULT '' NOT NULL,
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNUSERABSNCE_PK PRIMARY KEY (EMPLYR_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNUSERABSNCE IS '사용자부재'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNUSERABSNCE.EMPLYR_ID IS '업무사용자ID'; 
CREATE COMMENT ON COLUMN LETTNUSERABSNCE.USER_ABSNCE_AT IS '사용자부재여부'; 
CREATE COMMENT ON COLUMN LETTNUSERABSNCE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNUSERABSNCE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNUSERABSNCE.LAST_UPDUSR_ID IS '최종수정자ID'; 
CREATE COMMENT ON COLUMN LETTNUSERABSNCE.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TS_SYS_LOG_SUMMARY (시스템로그요약)
CREATE TABLE LETTSSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(765) NOT NULL,
  METHOD_NM varchar(180) NOT NULL,
  CREAT_CO numeric(10,0) ,
  UPDT_CO numeric(10,0) ,
  RDCNT numeric(10,0) ,
  DELETE_CO numeric(10,0) ,
  OUTPT_CO numeric(10,0) ,
  ERROR_CO numeric(10,0) ,
  CONSTRAINT LETTSSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTSSYSLOGSUMMARY IS '시스템로그요약';
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.OCCRRNC_DE IS '발생일'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.SRVC_NM IS '서비스명'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.METHOD_NM IS '메서드명'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.CREAT_CO IS '생성수'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.UPDT_CO IS '수정수'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.RDCNT IS '조회수'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.DELETE_CO IS '삭제수'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.OUTPT_CO IS '출력수'; 
CREATE COMMENT ON COLUMN LETTSSYSLOGSUMMARY.ERROR_CO IS '오류수'; 

-- View COM_VN_USER_MASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;