CREATE SCHEMA IF NOT EXISTS ebt AUTHORIZATION postgres;

SET search_path TO ebt;

-- IDS (ID's)
CREATE TABLE IF NOT EXISTS IDS (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID numeric(30,0) NOT NULL DEFAULT 0,
  PRIMARY KEY (TABLE_NAME)
);
-- 테이블에 대한 설명
COMMENT ON TABLE IDS IS 'IDS'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN IDS.TABLE_NAME IS '테이블명';
COMMENT ON COLUMN IDS.NEXT_ID IS '다음 ID';

-- LET_TC_CMMN_CL_CODE (공통분류코드)
CREATE TABLE IF NOT EXISTS LET_TC_CMMN_CL_CODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(60) DEFAULT NULL,
  CL_CODE_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CL_CODE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TC_CMMN_CL_CODE IS '공통분류코드'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.CL_CODE IS '분류코드'; 
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.CL_CODE_NM IS '분류코드명'; 
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.CL_CODE_DC IS '분류코드설명'; 
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LET_TC_CMMN_CL_CODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_CODE (공통코드)
CREATE TABLE IF NOT EXISTS LET_TC_CMMN_CODE (
  CODE_ID varchar(6) NOT NULL,
  CODE_ID_NM varchar(60) DEFAULT NULL,
  CODE_ID_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  CL_CODE char(3) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID),
  CONSTRAINT LET_TC_CMMN_CODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LET_TC_CMMN_CL_CODE (CL_CODE)
);
CREATE INDEX IF NOT EXISTS idx_LET_TC_CMMN_CODE_cl_code ON LET_TC_CMMN_CODE (CL_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TC_CMMN_CODE IS '공통코드';
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TC_CMMN_CODE.CODE_ID IS '코드ID'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.CODE_ID_NM IS '코드ID명'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.CODE_ID_DC IS '코드ID설명'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.CL_CODE IS '분류코드'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LET_TC_CMMN_CODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_DETAI_LCODE (공통상세코드)
CREATE TABLE IF NOT EXISTS LET_TC_CMMN_DETAIL_CODE (
  CODE_ID varchar(6) NOT NULL,
  CODE varchar(15) NOT NULL,
  CODE_NM varchar(60) DEFAULT NULL,
  CODE_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LET_TC_CMMN_DETAIL_CODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LET_TC_CMMN_CODE (CODE_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TC_CMMN_DETAIL_CODE IS '공통상세코드'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.CODE_ID IS '코드ID'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.CODE IS '코드'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.CODE_NM IS '코드명'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.CODE_DC IS '코드설명'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LET_TC_CMMN_DETAIL_CODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ORGNZT_INFO (조직정보)
CREATE TABLE IF NOT EXISTS LET_TN_ORGNZT_INFO (
  ORGNZT_ID char(20) NOT NULL DEFAULT '',
  ORGNZT_NM varchar(20) NOT NULL,
  ORGNZT_DC varchar(100) DEFAULT NULL,
  PRIMARY KEY (ORGNZT_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_ORGNZT_INFO IS '조직정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_ORGNZT_INFO.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN LET_TN_ORGNZT_INFO.ORGNZT_NM IS '조직명'; 
COMMENT ON COLUMN LET_TN_ORGNZT_INFO.ORGNZT_DC IS '조직설명'; 

-- LET_TN_AUTHOR_GROUP_INFO (권한그룹정보)
CREATE TABLE IF NOT EXISTS LET_TN_AUTHOR_GROUP_INFO (
  GROUP_ID char(20) NOT NULL DEFAULT '',
  GROUP_NM varchar(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar(100) DEFAULT NULL,
  PRIMARY KEY (GROUP_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_AUTHOR_GROUP_INFO IS '권한그룹정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_AUTHOR_GROUP_INFO.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LET_TN_AUTHOR_GROUP_INFO.GROUP_NM IS '그룹명'; 
COMMENT ON COLUMN LET_TN_AUTHOR_GROUP_INFO.GROUP_CREAT_DE IS '그룹생성일'; 
COMMENT ON COLUMN LET_TN_AUTHOR_GROUP_INFO.GROUP_DC IS '그룹설명'; 

-- LET_TN_AUTHOR_INFO (권한정보)
CREATE TABLE IF NOT EXISTS LET_TN_AUTHOR_INFO (
  AUTHOR_CODE varchar(30) NOT NULL DEFAULT '',
  AUTHOR_NM varchar(60) NOT NULL,
  AUTHOR_DC varchar(200) DEFAULT NULL,
  AUTHOR_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (AUTHOR_CODE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_AUTHOR_INFO IS '권한정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_AUTHOR_INFO.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN LET_TN_AUTHOR_INFO.AUTHOR_NM IS '권한명'; 
COMMENT ON COLUMN LET_TN_AUTHOR_INFO.AUTHOR_DC IS '권한설명'; 
COMMENT ON COLUMN LET_TN_AUTHOR_INFO.AUTHOR_CREAT_DE IS '권한생성일'; 

-- LET_TN_ROLES_HIERARCHY (롤 계층구조)
CREATE TABLE IF NOT EXISTS LET_TN_ROLES_HIERARCHY (
  PARNTS_ROLE varchar(30) NOT NULL,
  CHLDRN_ROLE varchar(30) NOT NULL,
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT LET_TN_ROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES LET_TN_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT LET_TN_ROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES LET_TN_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_ROLES_HIERARCHY_child ON LET_TN_ROLES_HIERARCHY (CHLDRN_ROLE);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_ROLES_HIERARCHY IS '롤 계층구조'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_ROLES_HIERARCHY.PARNTS_ROLE IS '부모롤'; 
COMMENT ON COLUMN LET_TN_ROLES_HIERARCHY.CHLDRN_ROLE IS '자식롤'; 

-- LET_TN_ROLE_INFO (롤정렬)
CREATE TABLE IF NOT EXISTS LET_TN_ROLE_INFO (
  ROLE_CODE varchar(50) NOT NULL DEFAULT '',
  ROLE_NM varchar(60) NOT NULL,
  ROLE_PTTRN varchar(300) DEFAULT NULL,
  ROLE_DC varchar(200) DEFAULT NULL,
  ROLE_TY varchar(80) DEFAULT NULL,
  ROLE_SORT varchar(10) DEFAULT NULL,
  ROLE_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (ROLE_CODE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_ROLE_INFO IS '롤정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_ROLE_INFO.ROLE_CODE IS '롤코드'; 
COMMENT ON COLUMN LET_TN_ROLE_INFO.ROLE_NM IS '롤명'; 
COMMENT ON COLUMN LET_TN_ROLE_INFO.ROLE_PTTRN IS '롤패턴'; 
COMMENT ON COLUMN LET_TN_ROLE_INFO.ROLE_DC IS '롤설명'; 
COMMENT ON COLUMN LET_TN_ROLE_INFO.ROLE_TY IS '롤유형'; 
COMMENT ON COLUMN LET_TN_ROLE_INFO.ROLE_SORT IS '롤정렬'; 
COMMENT ON COLUMN LET_TN_ROLE_INFO.ROLE_CREAT_DE IS '롤생성일'; 

-- LET_TN_AUTHOR_ROLE_RELATE (권한롤관계)
CREATE TABLE IF NOT EXISTS LET_TN_AUTHOR_ROLE_RELATE (
  AUTHOR_CODE varchar(30) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  CREAT_DT timestamp DEFAULT NULL,
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT LET_TN_AUTHOR_ROLE_RELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES LET_TN_ROLE_INFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT LET_TN_AUTHOR_ROLE_RELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES LET_TN_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_AUTHOR_ROLE_RELATE_role ON LET_TN_AUTHOR_ROLE_RELATE (ROLE_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_AUTHOR_ROLE_RELATE IS '권한롤관계'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_AUTHOR_ROLE_RELATE.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN LET_TN_AUTHOR_ROLE_RELATE.ROLE_CODE IS '롤코드'; 
COMMENT ON COLUMN LET_TN_AUTHOR_ROLE_RELATE.CREAT_DT IS '생성일시'; 

-- LET_TN_EMPLYR_INFO (업무사용자정보)
CREATE TABLE IF NOT EXISTS LET_TN_EMPLYR_INFO (
  EMPLYR_ID varchar(20) NOT NULL,
  ORGNZT_ID char(20) DEFAULT NULL,
  USER_NM varchar(60) NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  EMPL_NO varchar(20) DEFAULT NULL,
  IHIDNUM varchar(200) DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  HOUSE_ADRES varchar(100) DEFAULT NULL,
  PASSWORD_HINT varchar(100) NOT NULL,
  PASSWORD_CNSR varchar(100) NOT NULL,
  HOUSE_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  OFFM_TELNO varchar(20) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  EMAIL_ADRES varchar(50) DEFAULT NULL,
  OFCPS_NM varchar(60) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  PSTINST_CODE char(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE varchar(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(20) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT LET_TN_EMPLYR_INFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LET_TN_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LET_TN_EMPLYR_INFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LET_TN_ORGNZT_INFO (ORGNZT_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnempyrinfo_group_id ON LET_TN_EMPLYR_INFO (GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_lettnempyrinfo_orgnzt_id ON LET_TN_EMPLYR_INFO (ORGNZT_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_EMPLYR_INFO IS '업무사용자정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.USER_NM IS '사용자명'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.EMPL_NO IS '사원번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.IHIDNUM IS '주민등록번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.BRTHDY IS '생일'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.HOUSE_ADRES IS '주택주소'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.PASSWORD_HINT IS '비밀번호힌트'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.PASSWORD_CNSR IS '비밀번호정답'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.HOUSE_END_TELNO IS '주택끝전화번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.ZIP IS '우편번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.OFFM_TELNO IS '사무실전화번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.OFCPS_NM IS '직위명'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.PSTINST_CODE IS '소속기관코드'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.ESNTL_ID IS '고유ID'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.CRTFC_DN_VALUE IS '인증DN값'; 
COMMENT ON COLUMN LET_TN_EMPLYR_INFO.SBSCRB_DE IS '가입일자'; 

-- LET_TN_EMPLYR_SCRTY_ESTBS (사용자보안설정)
CREATE TABLE IF NOT EXISTS LET_TN_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(20) NOT NULL,
  MBER_TY_CODE varchar(15) DEFAULT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT LET_TN_EMPLYR_SCRTY_ESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES LET_TN_AUTHOR_INFO (AUTHOR_CODE)
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_EMPLYR_SCRTY_ESTBS_author ON LET_TN_EMPLYR_SCRTY_ESTBS (AUTHOR_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_EMPLYR_SCRTY_ESTBS IS '사용자보안설정'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_EMPLYR_SCRTY_ESTBS.SCRTY_DTRMN_TRGET_ID IS '보안설정대상ID'; 
COMMENT ON COLUMN LET_TN_EMPLYR_SCRTY_ESTBS.MBER_TY_CODE IS '회원유형코드'; 
COMMENT ON COLUMN LET_TN_EMPLYR_SCRTY_ESTBS.AUTHOR_CODE IS '권한코드'; 

-- LET_TN_TMPLAT_INFO (템플릿정보)
CREATE TABLE IF NOT EXISTS LET_TN_TMPLAT_INFO (
  TMPLAT_ID char(20) NOT NULL DEFAULT '',
  TMPLAT_NM varchar(255) DEFAULT NULL,
  TMPLAT_COURS varchar(2000) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  TMPLAT_SE_CODE char(6) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (TMPLAT_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_TMPLAT_INFO IS '템플릿정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.TMPLAT_ID IS '템플릿ID'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.TMPLAT_NM IS '템플릿명'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.TMPLAT_COURS IS '템플릿경로'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.TMPLAT_SE_CODE IS '템플릿구분코드'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LET_TN_TMPLAT_INFO.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_BBS_MASTER (게시판마스터)
CREATE TABLE IF NOT EXISTS LET_TN_BBS_MASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(255) NOT NULL,
  BBS_INTRCN varchar(2400) DEFAULT NULL,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) DEFAULT NULL,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) DEFAULT NULL,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_BBS_MASTER IS '게시판마스터'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_BBS_MASTER.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.BBS_NM IS '게시판명'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.BBS_INTRCN IS '게시판소개'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.BBS_TY_CODE IS '게시판유형코드'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.REPLY_POSBL_AT IS '답장가능여부'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.FILE_ATCH_POSBL_AT IS '파일첨부가능여부'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.ATCH_POSBL_FILE_NUMBER IS '첨부가능파일숫자'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.ATCH_POSBL_FILE_SIZE IS '첨부가능파일사이즈'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.TMPLAT_ID IS '템플릿ID'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_BBS_USE (게시판활용)
CREATE TABLE IF NOT EXISTS LET_TN_BBS_USE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) NOT NULL DEFAULT '',
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LET_TN_BBS_USE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LET_TN_BBS_MASTER (BBS_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_BBS_USE IS '게시판활용'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_BBS_USE.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LET_TN_BBS_USE.TRGET_ID IS '대상ID'; 
COMMENT ON COLUMN LET_TN_BBS_USE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LET_TN_BBS_USE.REGIST_SE_CODE IS '등록구분코드'; 
COMMENT ON COLUMN LET_TN_BBS_USE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TN_BBS_USE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TN_BBS_USE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LET_TN_BBS_USE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_BBS (게시판)
CREATE TABLE IF NOT EXISTS LET_TN_BBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) DEFAULT NULL,
  NTT_SJ varchar(2000) DEFAULT NULL,
  NTT_CN text,
  ANSWER_AT char(1) DEFAULT NULL,
  PARNTSCTT_NO numeric(10,0) DEFAULT NULL,
  ANSWER_LC integer DEFAULT NULL,
  SORT_ORDR numeric(8,0) DEFAULT NULL,
  RDCNT numeric(10,0) DEFAULT NULL,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) DEFAULT NULL,
  NTCE_ENDDE char(20) DEFAULT NULL,
  NTCR_ID varchar(20) DEFAULT NULL,
  NTCR_NM varchar(20) DEFAULT NULL,
  PASSWORD varchar(200) DEFAULT NULL,
  ATCH_FILE_ID char(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT LET_TN_BBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LET_TN_BBS_MASTER (BBS_ID)
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_BBS_bbs_id ON LET_TN_BBS (BBS_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_BBS IS '게시판'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_BBS.NTT_ID IS '게시물ID'; 
COMMENT ON COLUMN LET_TN_BBS.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LET_TN_BBS.NTT_NO IS '게시물번호'; 
COMMENT ON COLUMN LET_TN_BBS.NTT_SJ IS '게시물제목'; 
COMMENT ON COLUMN LET_TN_BBS.NTT_CN IS '게시물내용'; 
COMMENT ON COLUMN LET_TN_BBS.ANSWER_AT IS '댓글여부'; 
COMMENT ON COLUMN LET_TN_BBS.PARNTSCTT_NO IS '부모글번호'; 
COMMENT ON COLUMN LET_TN_BBS.ANSWER_LC IS '댓글위치'; 
COMMENT ON COLUMN LET_TN_BBS.SORT_ORDR IS '정렬순서'; 
COMMENT ON COLUMN LET_TN_BBS.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LET_TN_BBS.RDCNT IS '조회수'; 
COMMENT ON COLUMN LET_TN_BBS.NTCE_BGNDE IS '게시시작일'; 
COMMENT ON COLUMN LET_TN_BBS.NTCE_ENDDE IS '게시종료일'; 
COMMENT ON COLUMN LET_TN_BBS.NTCR_ID IS '게시자ID'; 
COMMENT ON COLUMN LET_TN_BBS.NTCR_NM IS '게시자명'; 
COMMENT ON COLUMN LET_TN_BBS.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN LET_TN_BBS.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN LET_TN_BBS.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TN_BBS.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TN_BBS.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LET_TN_BBS.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_ZIP (우편번호)
CREATE TABLE IF NOT EXISTS LET_TC_ZIP (
  ZIP varchar(6) NOT NULL,
  SN numeric(10,0) NOT NULL DEFAULT 0,
  CTPRVN_NM varchar(20) DEFAULT NULL,
  SIGNGU_NM varchar(20) DEFAULT NULL,
  EMD_NM varchar(60) DEFAULT NULL,
  LI_BULD_NM varchar(60) DEFAULT NULL,
  LNBR_DONG_HO varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (ZIP,SN)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TC_ZIP IS '우편번호'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TC_ZIP.ZIP IS '우편번호'; 
COMMENT ON COLUMN LET_TC_ZIP.SN IS '일련번호'; 
COMMENT ON COLUMN LET_TC_ZIP.CTPRVN_NM IS '시도명'; 
COMMENT ON COLUMN LET_TC_ZIP.SIGNGU_NM IS '시군구명'; 
COMMENT ON COLUMN LET_TC_ZIP.EMD_NM IS '읍면동명'; 
COMMENT ON COLUMN LET_TC_ZIP.LI_BULD_NM IS '리건물명'; 
COMMENT ON COLUMN LET_TC_ZIP.LNBR_DONG_HO IS '번지동호'; 
COMMENT ON COLUMN LET_TC_ZIP.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TC_ZIP.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TC_ZIP.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LET_TC_ZIP.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TH_EMPLYR_INFO_CHANGE_DTLS (업무사용자정보변경내역)
CREATE TABLE IF NOT EXISTS LET_TH_EMPLYR_INFO_CHANGE_DTLS (
  EMPLYR_ID varchar(20) NOT NULL,
  CHANGE_DE timestamp NOT NULL,
  ORGNZT_ID char(20) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  EMPL_NO varchar(20) DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  HOUSE_ADRES varchar(100) DEFAULT NULL,
  HOUSE_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  OFFM_TELNO varchar(20) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  EMAIL_ADRES varchar(50) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  PSTINST_CODE char(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE varchar(15) DEFAULT NULL,
  ESNTL_ID char(20) DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TH_EMPLYR_INFO_CHANGE_DTLS IS '업무사용자정보변경내역'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.CHANGE_DE IS '변경일'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.EMPL_NO IS '사원번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.BRTHDY IS '생일'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.HOUSE_ADRES IS '주택주소'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.HOUSE_END_TELNO IS '주택끝전화번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.ZIP IS '우편번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.OFFM_TELNO IS '사무실전화번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.PSTINST_CODE IS '소속기관코드'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
COMMENT ON COLUMN LET_TH_EMPLYR_INFO_CHANGE_DTLS.ESNTL_ID IS '고유ID'; 

-- LET_TN_BBS_MASTER_OPTN (게시판마스터옵션)
CREATE TABLE IF NOT EXISTS LET_TN_BBS_MASTER_OPTN (
  BBS_ID char(20) NOT NULL DEFAULT '',
  ANSWER_AT char(1) NOT NULL DEFAULT '',
  STSFDG_AT char(1) NOT NULL DEFAULT '',
  FRST_REGIST_PNTTM timestamp NOT NULL DEFAULT '1900-01-01 00:00:00',
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL DEFAULT '',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_BBS_MASTER_OPTN IS '게시판마스터옵션'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_BBS_MASTER_OPTN.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER_OPTN.ANSWER_AT IS '댓글여부'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER_OPTN.STSFDG_AT IS '만족도여부'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER_OPTN.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER_OPTN.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER_OPTN.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TN_BBS_MASTER_OPTN.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ENTRPRS_MBER (기업회원)
CREATE TABLE IF NOT EXISTS LET_TN_ENTRPRS_MBER (
  ENTRPRS_MBER_ID varchar(20) NOT NULL DEFAULT '',
  ENTRPRS_SE_CODE char(15) DEFAULT NULL,
  BIZRNO varchar(10) DEFAULT NULL,
  JURIRNO varchar(13) DEFAULT NULL,
  CMPNY_NM varchar(60) NOT NULL,
  CXFC varchar(50) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRES varchar(100) DEFAULT NULL,
  ENTRPRS_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  INDUTY_CODE char(15) DEFAULT NULL,
  APPLCNT_NM varchar(50) DEFAULT NULL,
  APPLCNT_IHIDNUM varchar(200) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  ENTRPRS_MBER_STTUS varchar(15) DEFAULT NULL,
  ENTRPRS_MBER_PASSWORD varchar(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(100) NOT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ENTRPRS_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  APPLCNT_EMAIL_ADRES varchar(50) DEFAULT NULL,
  ESNTL_ID char(20) NOT NULL,
  PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT LET_TN_ENTRPRS_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LET_TN_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_ENTRPRS_MBER_group_id ON LET_TN_ENTRPRS_MBER (GROUP_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_ENTRPRS_MBER IS '기업회원'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_MBER_ID IS '기업회원ID'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_SE_CODE IS '기업구분코드'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.BIZRNO IS '사업자등록번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.JURIRNO IS '법인등록번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.CMPNY_NM IS '회사명'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.CXFC IS '대표이사'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ZIP IS '우편번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ADRES IS '주소'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_MIDDLE_TELNO IS '기업중간전화번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.INDUTY_CODE IS '업종코드'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.APPLCNT_NM IS '신청인명'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.APPLCNT_IHIDNUM IS '신청인주민등록번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_MBER_STTUS IS '기업회원상태'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_MBER_PASSWORD IS '기업회원비밀번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_MBER_PASSWORD_HINT IS '기업회원비밀번호힌트'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_MBER_PASSWORD_CNSR IS '기업회원비밀번호정답'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ENTRPRS_END_TELNO IS '기업끝전화번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.APPLCNT_EMAIL_ADRES IS '신청자이메일주소'; 
COMMENT ON COLUMN LET_TN_ENTRPRS_MBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_FILE (파일속성)
CREATE TABLE IF NOT EXISTS LET_TN_FILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT timestamp NOT NULL,
  USE_AT char(1) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_FILE IS '파일속성'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_FILE.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN LET_TN_FILE.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN LET_TN_FILE.USE_AT IS '사용여부'; 

-- LET_TN_FILE_DETAIL (파일상세정보)
CREATE TABLE IF NOT EXISTS LET_TN_FILE_DETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(2000) NOT NULL,
  STRE_FILE_NM varchar(255) NOT NULL,
  ORIGNL_FILE_NM varchar(255) DEFAULT NULL,
  FILE_EXTSN varchar(20) NOT NULL,
  FILE_CN text,
  FILE_SIZE numeric(8,0) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LET_TN_FILE_DETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LET_TN_FILE (ATCH_FILE_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_FILE_DETAIL IS '파일상세정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_FILE_DETAIL.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN LET_TN_FILE_DETAIL.FILE_SN IS '파일순번'; 
COMMENT ON COLUMN LET_TN_FILE_DETAIL.FILE_STRE_COURS IS '파일저장경로'; 
COMMENT ON COLUMN LET_TN_FILE_DETAIL.STRE_FILE_NM IS '저장파일명'; 
COMMENT ON COLUMN LET_TN_FILE_DETAIL.ORIGNL_FILE_NM IS '원파일명'; 
COMMENT ON COLUMN LET_TN_FILE_DETAIL.FILE_EXTSN IS '파일확장자'; 
COMMENT ON COLUMN LET_TN_FILE_DETAIL.FILE_CN IS '파일내용'; 
COMMENT ON COLUMN LET_TN_FILE_DETAIL.FILE_SIZE IS '파일크기'; 

-- LET_TN_GNRL_MBER (일반회원)
CREATE TABLE IF NOT EXISTS LET_TN_GNRL_MBER (
  MBER_ID varchar(20) NOT NULL DEFAULT '',
  PASSWORD varchar(200) NOT NULL,
  PASSWORD_HINT varchar(100) DEFAULT NULL,
  PASSWORD_CNSR varchar(100) DEFAULT NULL,
  IHIDNUM varchar(200) DEFAULT NULL,
  MBER_NM varchar(50) NOT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRES varchar(100) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  MBER_STTUS varchar(15) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  END_TELNO varchar(4) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  MBER_FXNUM varchar(20) DEFAULT NULL,
  MBER_EMAIL_ADRES varchar(50) DEFAULT NULL,
  MIDDLE_TELNO varchar(4) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  ESNTL_ID char(20) NOT NULL,
  PRIMARY KEY (MBER_ID),
  CONSTRAINT LET_TN_GNRL_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LET_TN_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_GNRL_MBER_group_id ON LET_TN_GNRL_MBER (GROUP_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_GNRL_MBER IS '일반회원'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_GNRL_MBER.MBER_ID IS '회원ID'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.PASSWORD_HINT IS '비밀번호힌트'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.PASSWORD_CNSR IS '비밀번호정답'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.IHIDNUM IS '주민등록번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.MBER_NM IS '회원명'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.ZIP IS '우편번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.ADRES IS '주소'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.MBER_STTUS IS '회원상태'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.END_TELNO IS '끝전화번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.MBER_FXNUM IS '회원팩스번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.MBER_EMAIL_ADRES IS '회원이메일주소'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.MIDDLE_TELNO IS '중간전화번호'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN LET_TN_GNRL_MBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_LOGIN_LOG (접속로그)
CREATE TABLE IF NOT EXISTS LET_TN_LOGIN_LOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(20) DEFAULT NULL,
  CONECT_IP varchar(23) DEFAULT NULL,
  CONECT_MTHD char(4) DEFAULT NULL,
  ERROR_OCCRRNC_AT char(1) DEFAULT NULL,
  ERROR_CODE char(3) DEFAULT NULL,
  CREAT_DT timestamp DEFAULT NULL,
  PRIMARY KEY (LOG_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_LOGIN_LOG IS '접속로그'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_LOGIN_LOG.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN LET_TN_LOGIN_LOG.CONECT_ID IS '접속ID'; 
COMMENT ON COLUMN LET_TN_LOGIN_LOG.CONECT_IP IS '접속IP'; 
COMMENT ON COLUMN LET_TN_LOGIN_LOG.CONECT_MTHD IS '접속방식'; 
COMMENT ON COLUMN LET_TN_LOGIN_LOG.ERROR_OCCRRNC_AT IS '오류발생여부'; 
COMMENT ON COLUMN LET_TN_LOGIN_LOG.ERROR_CODE IS '오류코드'; 
COMMENT ON COLUMN LET_TN_LOGIN_LOG.CREAT_DT IS '생성일시'; 

-- LET_TN_LOGIN_POLICY (로그인정책)
CREATE TABLE IF NOT EXISTS LET_TN_LOGIN_POLICY (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  IP_INFO varchar(23) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMTT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_LOGIN_POLICY IS '로그인정책'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.IP_INFO IS 'IP정보'; 
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.DPLCT_PERM_AT IS '중복허용여부'; 
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.LMTT_AT IS '제한여부'; 
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LET_TN_LOGIN_POLICY.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_PROGRM_LIST (프로그램목록)
CREATE TABLE IF NOT EXISTS LET_TN_PROGRM_LIST (
  PROGRM_FILE_NM varchar(60) NOT NULL DEFAULT '',
  PROGRM_STRE_PATH varchar(100) NOT NULL,
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL,
  PROGRM_DC varchar(200) DEFAULT NULL,
  URL varchar(100) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_PROGRM_LIST IS '프로그램목록'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_PROGRM_LIST.PROGRM_FILE_NM IS '프로그램파일명'; 
COMMENT ON COLUMN LET_TN_PROGRM_LIST.PROGRM_STRE_PATH IS '프로그램저장경로'; 
COMMENT ON COLUMN LET_TN_PROGRM_LIST.PROGRM_KOREAN_NM IS '프로그램한글명'; 
COMMENT ON COLUMN LET_TN_PROGRM_LIST.PROGRM_DC IS '프로그램설명'; 
COMMENT ON COLUMN LET_TN_PROGRM_LIST.URL IS 'URL'; 

-- LET_TN_MENU_INFO (메뉴정보)
CREATE TABLE IF NOT EXISTS LET_TN_MENU_INFO (
  MENU_NM varchar(60) NOT NULL,
  PROGRM_FILE_NM varchar(60) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0) DEFAULT NULL,
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC varchar(250) DEFAULT NULL,
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL,
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL,
  PRIMARY KEY (MENU_NO),
  CONSTRAINT LET_TN_MENU_INFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES LET_TN_MENU_INFO (MENU_NO),
  CONSTRAINT LET_TN_MENU_INFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES LET_TN_PROGRM_LIST (PROGRM_FILE_NM) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_MENU_INFO_progrm_file_nm ON LET_TN_MENU_INFO (PROGRM_FILE_NM);
CREATE INDEX IF NOT EXISTS idx_LET_TN_MENU_INFO_upper_menu_no ON LET_TN_MENU_INFO (UPPER_MENU_NO);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_MENU_INFO IS '메뉴정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_MENU_INFO.MENU_NO IS '메뉴번호'; 
COMMENT ON COLUMN LET_TN_MENU_INFO.UPPER_MENU_NO IS '상위메뉴번호'; 
COMMENT ON COLUMN LET_TN_MENU_INFO.MENU_NM IS '메뉴명'; 
COMMENT ON COLUMN LET_TN_MENU_INFO.PROGRM_FILE_NM IS '프로그램파일명'; 
COMMENT ON COLUMN LET_TN_MENU_INFO.MENU_ORDR IS '메뉴순서'; 
COMMENT ON COLUMN LET_TN_MENU_INFO.MENU_DC IS '메뉴설명'; 
COMMENT ON COLUMN LET_TN_MENU_INFO.RELATE_IMAGE_PATH IS '관계이미지경로'; 
COMMENT ON COLUMN LET_TN_MENU_INFO.RELATE_IMAGE_NM IS '관계이미지명'; 

-- LET_TN_MENU_CREAT_DTLS (메뉴생성내역)
CREATE TABLE IF NOT EXISTS LET_TN_MENU_CREAT_DTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL,
  PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT LET_TN_MENU_CREAT_DTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES LET_TN_AUTHOR_INFO (AUTHOR_CODE),
  CONSTRAINT LET_TN_MENU_CREAT_DTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES LET_TN_MENU_INFO (MENU_NO) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_LET_TN_MENU_CREAT_DTLS_mapng ON LET_TN_MENU_CREAT_DTLS (MAPNG_CREAT_ID);
CREATE INDEX IF NOT EXISTS idx_LET_TN_MENU_CREAT_DTLS_author ON LET_TN_MENU_CREAT_DTLS (AUTHOR_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_MENU_CREAT_DTLS IS '메뉴생성내역'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_MENU_CREAT_DTLS.MENU_NO IS '메뉴번호'; 
COMMENT ON COLUMN LET_TN_MENU_CREAT_DTLS.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN LET_TN_MENU_CREAT_DTLS.MAPNG_CREAT_ID IS '매핑생성ID'; 

-- LET_TN_USER_ABSNCE (사용자부재)
CREATE TABLE IF NOT EXISTS LET_TN_USER_ABSNCE (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TN_USER_ABSNCE IS '사용자부재'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TN_USER_ABSNCE.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LET_TN_USER_ABSNCE.USER_ABSNCE_AT IS '사용자부재여부'; 
COMMENT ON COLUMN LET_TN_USER_ABSNCE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LET_TN_USER_ABSNCE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LET_TN_USER_ABSNCE.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LET_TN_USER_ABSNCE.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TS_SYS_LOG_SUMMARY (시스템로그요약)
CREATE TABLE IF NOT EXISTS LET_TS_SYS_LOG_SUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(255) NOT NULL,
  METHOD_NM varchar(60) NOT NULL,
  CREAT_CO numeric(10,0) DEFAULT NULL,
  UPDT_CO numeric(10,0) DEFAULT NULL,
  RDCNT numeric(10,0) DEFAULT NULL,
  DELETE_CO numeric(10,0) DEFAULT NULL,
  OUTPT_CO numeric(10,0) DEFAULT NULL,
  ERROR_CO numeric(10,0) DEFAULT NULL,
  PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LET_TS_SYS_LOG_SUMMARY IS '시스템로그요약';
-- 컬럼에 대한 설명
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.OCCRRNC_DE IS '발생일'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.SRVC_NM IS '서비스명'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.METHOD_NM IS '메서드명'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.CREAT_CO IS '생성수'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.UPDT_CO IS '수정수'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.RDCNT IS '조회수'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.DELETE_CO IS '삭제수'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.OUTPT_CO IS '출력수'; 
COMMENT ON COLUMN LET_TS_SYS_LOG_SUMMARY.ERROR_CO IS '오류수'; 

-- View COM_VN_USER_MASTER
CREATE OR REPLACE VIEW COM_VN_USER_MASTER (
  ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID
) AS
        SELECT ESNTL_ID, MBER_ID AS USER_ID,PASSWORD,MBER_NM AS USER_NM,ZIP AS USER_ZIP,ADRES AS USER_ADRES,MBER_EMAIL_ADRES AS USER_EMAIL,' ' AS GROUP_ID,'GNR' AS USER_SE, ' ' AS ORGNZT_ID
        FROM LET_TN_GNRL_MBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID AS USER_ID,PASSWORD,USER_NM,ZIP AS USER_ZIP,HOUSE_ADRES AS USER_ADRES,EMAIL_ADRES AS USER_EMAIL,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LET_TN_EMPLYR_INFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID AS USER_ID,ENTRPRS_MBER_PASSWORD AS PASSWORD,CMPNY_NM AS USER_NM,ZIP AS USER_ZIP,ADRES AS USER_ADRES,APPLCNT_EMAIL_ADRES AS USER_EMAIL,' ' AS GROUP_ID,'ENT' AS USER_SE, ' ' AS ORGNZT_ID
        FROM LET_TN_ENTRPRS_MBER
;


