apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: egov-ebt-mysql
    app.kubernetes.io/part-of: egovframe-template
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: egov-ebt-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
