apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app.kubernetes.io/name: egov-ebt-mysql
    app.kubernetes.io/part-of: egovframe-template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
