CREATE SCHEMA IF NOT EXISTS ebt AUTHORIZATION postgres;

SET search_path TO ebt;

-- IDS (ID's)
CREATE TABLE IF NOT EXISTS IDS (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID numeric(30,0) NOT NULL DEFAULT 0,
  PRIMARY KEY (TABLE_NAME)
);
-- 테이블에 대한 설명
COMMENT ON TABLE IDS IS 'IDS'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN IDS.TABLE_NAME IS '테이블명';
COMMENT ON COLUMN IDS.NEXT_ID IS '다음 ID';

-- LET_TC_CMMN_CL_CODE (공통분류코드)
CREATE TABLE IF NOT EXISTS LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(60) DEFAULT NULL,
  CL_CODE_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CL_CODE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTCCMMNCLCODE IS '공통분류코드'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE IS '분류코드'; 
COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE_NM IS '분류코드명'; 
COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE_DC IS '분류코드설명'; 
COMMENT ON COLUMN LETTCCMMNCLCODE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LETTCCMMNCLCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTCCMMNCLCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTCCMMNCLCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTCCMMNCLCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_CODE (공통코드)
CREATE TABLE IF NOT EXISTS LETTCCMMNCODE (
  CODE_ID varchar(6) NOT NULL,
  CODE_ID_NM varchar(60) DEFAULT NULL,
  CODE_ID_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  CL_CODE char(3) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
);
CREATE INDEX IF NOT EXISTS idx_lettccmmncode_cl_code ON LETTCCMMNCODE (CL_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTCCMMNCODE IS '공통코드';
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID IS '코드ID'; 
COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID_NM IS '코드ID명'; 
COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID_DC IS '코드ID설명'; 
COMMENT ON COLUMN LETTCCMMNCODE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LETTCCMMNCODE.CL_CODE IS '분류코드'; 
COMMENT ON COLUMN LETTCCMMNCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTCCMMNCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTCCMMNCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTCCMMNCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_DETAI_LCODE (공통상세코드)
CREATE TABLE IF NOT EXISTS LETTCCMMNDETAILCODE (
  CODE_ID varchar(6) NOT NULL,
  CODE varchar(15) NOT NULL,
  CODE_NM varchar(60) DEFAULT NULL,
  CODE_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTCCMMNDETAILCODE IS '공통상세코드'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_ID IS '코드ID'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE IS '코드'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_NM IS '코드명'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_DC IS '코드설명'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTCCMMNDETAILCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ORGNZT_INFO (조직정보)
CREATE TABLE IF NOT EXISTS LETTNORGNZTINFO (
  ORGNZT_ID char(20) NOT NULL DEFAULT '',
  ORGNZT_NM varchar(20) NOT NULL,
  ORGNZT_DC varchar(100) DEFAULT NULL,
  PRIMARY KEY (ORGNZT_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNORGNZTINFO IS '조직정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_NM IS '조직명'; 
COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_DC IS '조직설명'; 

-- LET_TN_AUTHOR_GROUP_INFO (권한그룹정보)
CREATE TABLE IF NOT EXISTS LETTNAUTHORGROUPINFO (
  GROUP_ID char(20) NOT NULL DEFAULT '',
  GROUP_NM varchar(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar(100) DEFAULT NULL,
  PRIMARY KEY (GROUP_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNAUTHORGROUPINFO IS '권한그룹정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_NM IS '그룹명'; 
COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_CREAT_DE IS '그룹생성일'; 
COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_DC IS '그룹설명'; 

-- LET_TN_AUTHOR_INFO (권한정보)
CREATE TABLE IF NOT EXISTS LETTNAUTHORINFO (
  AUTHOR_CODE varchar(30) NOT NULL DEFAULT '',
  AUTHOR_NM varchar(60) NOT NULL,
  AUTHOR_DC varchar(200) DEFAULT NULL,
  AUTHOR_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (AUTHOR_CODE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNAUTHORINFO IS '권한정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_NM IS '권한명'; 
COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_DC IS '권한설명'; 
COMMENT ON COLUMN LETTNAUTHORINFO.AUTHOR_CREAT_DE IS '권한생성일'; 

-- LET_TN_ROLES_HIERARCHY (롤 계층구조)
CREATE TABLE IF NOT EXISTS LETTNROLES_HIERARCHY (
  PARNTS_ROLE varchar(30) NOT NULL,
  CHLDRN_ROLE varchar(30) NOT NULL,
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnroles_hierarchy_child ON LETTNROLES_HIERARCHY (CHLDRN_ROLE);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNROLES_HIERARCHY IS '롤 계층구조'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNROLES_HIERARCHY.PARNTS_ROLE IS '부모롤'; 
COMMENT ON COLUMN LETTNROLES_HIERARCHY.CHLDRN_ROLE IS '자식롤'; 

-- LET_TN_ROLE_INFO (롤정렬)
CREATE TABLE IF NOT EXISTS LETTNROLEINFO (
  ROLE_CODE varchar(50) NOT NULL DEFAULT '',
  ROLE_NM varchar(60) NOT NULL,
  ROLE_PTTRN varchar(300) DEFAULT NULL,
  ROLE_DC varchar(200) DEFAULT NULL,
  ROLE_TY varchar(80) DEFAULT NULL,
  ROLE_SORT varchar(10) DEFAULT NULL,
  ROLE_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (ROLE_CODE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNROLEINFO IS '롤정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNROLEINFO.ROLE_CODE IS '롤코드'; 
COMMENT ON COLUMN LETTNROLEINFO.ROLE_NM IS '롤명'; 
COMMENT ON COLUMN LETTNROLEINFO.ROLE_PTTRN IS '롤패턴'; 
COMMENT ON COLUMN LETTNROLEINFO.ROLE_DC IS '롤설명'; 
COMMENT ON COLUMN LETTNROLEINFO.ROLE_TY IS '롤유형'; 
COMMENT ON COLUMN LETTNROLEINFO.ROLE_SORT IS '롤정렬'; 
COMMENT ON COLUMN LETTNROLEINFO.ROLE_CREAT_DE IS '롤생성일'; 

-- LET_TN_AUTHOR_ROLE_RELATE (권한롤관계)
CREATE TABLE IF NOT EXISTS LETTNAUTHORROLERELATE (
  AUTHOR_CODE varchar(30) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  CREAT_DT timestamp DEFAULT NULL,
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES LETTNROLEINFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnauthorrolerelate_role ON LETTNAUTHORROLERELATE (ROLE_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNAUTHORROLERELATE IS '권한롤관계'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNAUTHORROLERELATE.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN LETTNAUTHORROLERELATE.ROLE_CODE IS '롤코드'; 
COMMENT ON COLUMN LETTNAUTHORROLERELATE.CREAT_DT IS '생성일시'; 

-- LET_TN_EMPLYR_INFO (업무사용자정보)
CREATE TABLE IF NOT EXISTS LETTNEMPLYRINFO (
  EMPLYR_ID varchar(20) NOT NULL,
  ORGNZT_ID char(20) DEFAULT NULL,
  USER_NM varchar(60) NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  EMPL_NO varchar(20) DEFAULT NULL,
  IHIDNUM varchar(200) DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  HOUSE_ADRES varchar(100) DEFAULT NULL,
  PASSWORD_HINT varchar(100) NOT NULL,
  PASSWORD_CNSR varchar(100) NOT NULL,
  HOUSE_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  OFFM_TELNO varchar(20) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  EMAIL_ADRES varchar(50) DEFAULT NULL,
  OFCPS_NM varchar(60) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  PSTINST_CODE char(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE varchar(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(20) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnempyrinfo_group_id ON LETTNEMPLYRINFO (GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_lettnempyrinfo_orgnzt_id ON LETTNEMPLYRINFO (ORGNZT_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNEMPLYRINFO IS '업무사용자정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNEMPLYRINFO.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.USER_NM IS '사용자명'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.EMPL_NO IS '사원번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.IHIDNUM IS '주민등록번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.BRTHDY IS '생일'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_ADRES IS '주택주소'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD_HINT IS '비밀번호힌트'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD_CNSR IS '비밀번호정답'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_END_TELNO IS '주택끝전화번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.ZIP IS '우편번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.OFFM_TELNO IS '사무실전화번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.OFCPS_NM IS '직위명'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.PSTINST_CODE IS '소속기관코드'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.ESNTL_ID IS '고유ID'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.CRTFC_DN_VALUE IS '인증DN값'; 
COMMENT ON COLUMN LETTNEMPLYRINFO.SBSCRB_DE IS '가입일자'; 

-- LET_TN_EMPLYR_SCRTY_ESTBS (사용자보안설정)
CREATE TABLE IF NOT EXISTS LETTNEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(20) NOT NULL,
  MBER_TY_CODE varchar(15) DEFAULT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT LETTNEMPLYRSCRTYESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE)
);
CREATE INDEX IF NOT EXISTS idx_lettnemplyrscrtyestbs_author ON LETTNEMPLYRSCRTYESTBS (AUTHOR_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNEMPLYRSCRTYESTBS IS '사용자보안설정'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNEMPLYRSCRTYESTBS.SCRTY_DTRMN_TRGET_ID IS '보안설정대상ID'; 
COMMENT ON COLUMN LETTNEMPLYRSCRTYESTBS.MBER_TY_CODE IS '회원유형코드'; 
COMMENT ON COLUMN LETTNEMPLYRSCRTYESTBS.AUTHOR_CODE IS '권한코드'; 

-- LET_TN_TMPLAT_INFO (템플릿정보)
CREATE TABLE IF NOT EXISTS LETTNTMPLATINFO (
  TMPLAT_ID char(20) NOT NULL DEFAULT '',
  TMPLAT_NM varchar(255) DEFAULT NULL,
  TMPLAT_COURS varchar(2000) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  TMPLAT_SE_CODE char(6) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (TMPLAT_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNTMPLATINFO IS '템플릿정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_ID IS '템플릿ID'; 
COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_NM IS '템플릿명'; 
COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_COURS IS '템플릿경로'; 
COMMENT ON COLUMN LETTNTMPLATINFO.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LETTNTMPLATINFO.TMPLAT_SE_CODE IS '템플릿구분코드'; 
COMMENT ON COLUMN LETTNTMPLATINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNTMPLATINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNTMPLATINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LETTNTMPLATINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_BBS_MASTER (게시판마스터)
CREATE TABLE IF NOT EXISTS LETTNBBSMASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(255) NOT NULL,
  BBS_INTRCN varchar(2400) DEFAULT NULL,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) DEFAULT NULL,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) DEFAULT NULL,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNBBSMASTER IS '게시판마스터'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNBBSMASTER.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LETTNBBSMASTER.BBS_NM IS '게시판명'; 
COMMENT ON COLUMN LETTNBBSMASTER.BBS_INTRCN IS '게시판소개'; 
COMMENT ON COLUMN LETTNBBSMASTER.BBS_TY_CODE IS '게시판유형코드'; 
COMMENT ON COLUMN LETTNBBSMASTER.REPLY_POSBL_AT IS '답장가능여부'; 
COMMENT ON COLUMN LETTNBBSMASTER.FILE_ATCH_POSBL_AT IS '파일첨부가능여부'; 
COMMENT ON COLUMN LETTNBBSMASTER.ATCH_POSBL_FILE_NUMBER IS '첨부가능파일숫자'; 
COMMENT ON COLUMN LETTNBBSMASTER.ATCH_POSBL_FILE_SIZE IS '첨부가능파일사이즈'; 
COMMENT ON COLUMN LETTNBBSMASTER.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LETTNBBSMASTER.TMPLAT_ID IS '템플릿ID'; 
COMMENT ON COLUMN LETTNBBSMASTER.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNBBSMASTER.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNBBSMASTER.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LETTNBBSMASTER.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_BBS_USE (게시판활용)
CREATE TABLE IF NOT EXISTS LETTNBBSUSE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) NOT NULL DEFAULT '',
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNBBSUSE IS '게시판활용'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNBBSUSE.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LETTNBBSUSE.TRGET_ID IS '대상ID'; 
COMMENT ON COLUMN LETTNBBSUSE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LETTNBBSUSE.REGIST_SE_CODE IS '등록구분코드'; 
COMMENT ON COLUMN LETTNBBSUSE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNBBSUSE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNBBSUSE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTNBBSUSE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_BBS (게시판)
CREATE TABLE IF NOT EXISTS LETTNBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) DEFAULT NULL,
  NTT_SJ varchar(2000) DEFAULT NULL,
  NTT_CN text,
  ANSWER_AT char(1) DEFAULT NULL,
  PARNTSCTT_NO numeric(10,0) DEFAULT NULL,
  ANSWER_LC integer DEFAULT NULL,
  SORT_ORDR numeric(8,0) DEFAULT NULL,
  RDCNT numeric(10,0) DEFAULT NULL,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) DEFAULT NULL,
  NTCE_ENDDE char(20) DEFAULT NULL,
  NTCR_ID varchar(20) DEFAULT NULL,
  NTCR_NM varchar(20) DEFAULT NULL,
  PASSWORD varchar(200) DEFAULT NULL,
  ATCH_FILE_ID char(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
);
CREATE INDEX IF NOT EXISTS idx_lettnbbs_bbs_id ON LETTNBBS (BBS_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNBBS IS '게시판'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNBBS.NTT_ID IS '게시물ID'; 
COMMENT ON COLUMN LETTNBBS.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LETTNBBS.NTT_NO IS '게시물번호'; 
COMMENT ON COLUMN LETTNBBS.NTT_SJ IS '게시물제목'; 
COMMENT ON COLUMN LETTNBBS.NTT_CN IS '게시물내용'; 
COMMENT ON COLUMN LETTNBBS.ANSWER_AT IS '댓글여부'; 
COMMENT ON COLUMN LETTNBBS.PARNTSCTT_NO IS '부모글번호'; 
COMMENT ON COLUMN LETTNBBS.ANSWER_LC IS '댓글위치'; 
COMMENT ON COLUMN LETTNBBS.SORT_ORDR IS '정렬순서'; 
COMMENT ON COLUMN LETTNBBS.USE_AT IS '사용여부'; 
COMMENT ON COLUMN LETTNBBS.RDCNT IS '조회수'; 
COMMENT ON COLUMN LETTNBBS.NTCE_BGNDE IS '게시시작일'; 
COMMENT ON COLUMN LETTNBBS.NTCE_ENDDE IS '게시종료일'; 
COMMENT ON COLUMN LETTNBBS.NTCR_ID IS '게시자ID'; 
COMMENT ON COLUMN LETTNBBS.NTCR_NM IS '게시자명'; 
COMMENT ON COLUMN LETTNBBS.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN LETTNBBS.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN LETTNBBS.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNBBS.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNBBS.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTNBBS.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_ZIP (우편번호)
CREATE TABLE IF NOT EXISTS LETTCZIP (
  ZIP varchar(6) NOT NULL,
  SN numeric(10,0) NOT NULL DEFAULT 0,
  CTPRVN_NM varchar(20) DEFAULT NULL,
  SIGNGU_NM varchar(20) DEFAULT NULL,
  EMD_NM varchar(60) DEFAULT NULL,
  LI_BULD_NM varchar(60) DEFAULT NULL,
  LNBR_DONG_HO varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (ZIP,SN)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTCZIP IS '우편번호'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTCZIP.ZIP IS '우편번호'; 
COMMENT ON COLUMN LETTCZIP.SN IS '일련번호'; 
COMMENT ON COLUMN LETTCZIP.CTPRVN_NM IS '시도명'; 
COMMENT ON COLUMN LETTCZIP.SIGNGU_NM IS '시군구명'; 
COMMENT ON COLUMN LETTCZIP.EMD_NM IS '읍면동명'; 
COMMENT ON COLUMN LETTCZIP.LI_BULD_NM IS '리건물명'; 
COMMENT ON COLUMN LETTCZIP.LNBR_DONG_HO IS '번지동호'; 
COMMENT ON COLUMN LETTCZIP.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTCZIP.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTCZIP.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTCZIP.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TH_EMPLYR_INFO_CHANGE_DTLS (업무사용자정보변경내역)
CREATE TABLE IF NOT EXISTS LETTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID varchar(20) NOT NULL,
  CHANGE_DE timestamp NOT NULL,
  ORGNZT_ID char(20) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  EMPL_NO varchar(20) DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  HOUSE_ADRES varchar(100) DEFAULT NULL,
  HOUSE_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  OFFM_TELNO varchar(20) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  EMAIL_ADRES varchar(50) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  PSTINST_CODE char(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE varchar(15) DEFAULT NULL,
  ESNTL_ID char(20) DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTHEMPLYRINFOCHANGEDTLS IS '업무사용자정보변경내역'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.CHANGE_DE IS '변경일'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMPL_NO IS '사원번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.BRTHDY IS '생일'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.HOUSE_ADRES IS '주택주소'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.HOUSE_END_TELNO IS '주택끝전화번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.ZIP IS '우편번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.OFFM_TELNO IS '사무실전화번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.PSTINST_CODE IS '소속기관코드'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
COMMENT ON COLUMN LETTHEMPLYRINFOCHANGEDTLS.ESNTL_ID IS '고유ID'; 

-- LET_TN_BBS_MASTER_OPTN (게시판마스터옵션)
CREATE TABLE IF NOT EXISTS LETTNBBSMASTEROPTN (
  BBS_ID char(20) NOT NULL DEFAULT '',
  ANSWER_AT char(1) NOT NULL DEFAULT '',
  STSFDG_AT char(1) NOT NULL DEFAULT '',
  FRST_REGIST_PNTTM timestamp NOT NULL DEFAULT '1900-01-01 00:00:00',
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL DEFAULT '',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNBBSMASTEROPTN IS '게시판마스터옵션'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNBBSMASTEROPTN.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN LETTNBBSMASTEROPTN.ANSWER_AT IS '댓글여부'; 
COMMENT ON COLUMN LETTNBBSMASTEROPTN.STSFDG_AT IS '만족도여부'; 
COMMENT ON COLUMN LETTNBBSMASTEROPTN.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNBBSMASTEROPTN.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTNBBSMASTEROPTN.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNBBSMASTEROPTN.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ENTRPRS_MBER (기업회원)
CREATE TABLE IF NOT EXISTS LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(20) NOT NULL DEFAULT '',
  ENTRPRS_SE_CODE char(15) DEFAULT NULL,
  BIZRNO varchar(10) DEFAULT NULL,
  JURIRNO varchar(13) DEFAULT NULL,
  CMPNY_NM varchar(60) NOT NULL,
  CXFC varchar(50) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRES varchar(100) DEFAULT NULL,
  ENTRPRS_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  INDUTY_CODE char(15) DEFAULT NULL,
  APPLCNT_NM varchar(50) DEFAULT NULL,
  APPLCNT_IHIDNUM varchar(200) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  ENTRPRS_MBER_STTUS varchar(15) DEFAULT NULL,
  ENTRPRS_MBER_PASSWORD varchar(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(100) NOT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ENTRPRS_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  APPLCNT_EMAIL_ADRES varchar(50) DEFAULT NULL,
  ESNTL_ID char(20) NOT NULL,
  PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnentrprsmber_group_id ON LETTNENTRPRSMBER (GROUP_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNENTRPRSMBER IS '기업회원'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_ID IS '기업회원ID'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_SE_CODE IS '기업구분코드'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.BIZRNO IS '사업자등록번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.JURIRNO IS '법인등록번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.CMPNY_NM IS '회사명'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.CXFC IS '대표이사'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ZIP IS '우편번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ADRES IS '주소'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MIDDLE_TELNO IS '기업중간전화번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.INDUTY_CODE IS '업종코드'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_NM IS '신청인명'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_IHIDNUM IS '신청인주민등록번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_STTUS IS '기업회원상태'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD IS '기업회원비밀번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_HINT IS '기업회원비밀번호힌트'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_CNSR IS '기업회원비밀번호정답'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_END_TELNO IS '기업끝전화번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_EMAIL_ADRES IS '신청자이메일주소'; 
COMMENT ON COLUMN LETTNENTRPRSMBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_FILE (파일속성)
CREATE TABLE IF NOT EXISTS LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT timestamp NOT NULL,
  USE_AT char(1) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNFILE IS '파일속성'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNFILE.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN LETTNFILE.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN LETTNFILE.USE_AT IS '사용여부'; 

-- LET_TN_FILE_DETAIL (파일상세정보)
CREATE TABLE IF NOT EXISTS LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(2000) NOT NULL,
  STRE_FILE_NM varchar(255) NOT NULL,
  ORIGNL_FILE_NM varchar(255) DEFAULT NULL,
  FILE_EXTSN varchar(20) NOT NULL,
  FILE_CN text,
  FILE_SIZE numeric(8,0) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNFILEDETAIL IS '파일상세정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNFILEDETAIL.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN LETTNFILEDETAIL.FILE_SN IS '파일순번'; 
COMMENT ON COLUMN LETTNFILEDETAIL.FILE_STRE_COURS IS '파일저장경로'; 
COMMENT ON COLUMN LETTNFILEDETAIL.STRE_FILE_NM IS '저장파일명'; 
COMMENT ON COLUMN LETTNFILEDETAIL.ORIGNL_FILE_NM IS '원파일명'; 
COMMENT ON COLUMN LETTNFILEDETAIL.FILE_EXTSN IS '파일확장자'; 
COMMENT ON COLUMN LETTNFILEDETAIL.FILE_CN IS '파일내용'; 
COMMENT ON COLUMN LETTNFILEDETAIL.FILE_SIZE IS '파일크기'; 

-- LET_TN_GNRL_MBER (일반회원)
CREATE TABLE IF NOT EXISTS LETTNGNRLMBER (
  MBER_ID varchar(20) NOT NULL DEFAULT '',
  PASSWORD varchar(200) NOT NULL,
  PASSWORD_HINT varchar(100) DEFAULT NULL,
  PASSWORD_CNSR varchar(100) DEFAULT NULL,
  IHIDNUM varchar(200) DEFAULT NULL,
  MBER_NM varchar(50) NOT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRES varchar(100) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  MBER_STTUS varchar(15) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  END_TELNO varchar(4) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  MBER_FXNUM varchar(20) DEFAULT NULL,
  MBER_EMAIL_ADRES varchar(50) DEFAULT NULL,
  MIDDLE_TELNO varchar(4) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  ESNTL_ID char(20) NOT NULL,
  PRIMARY KEY (MBER_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettngnrlmber_group_id ON LETTNGNRLMBER (GROUP_ID);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNGNRLMBER IS '일반회원'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNGNRLMBER.MBER_ID IS '회원ID'; 
COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD_HINT IS '비밀번호힌트'; 
COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD_CNSR IS '비밀번호정답'; 
COMMENT ON COLUMN LETTNGNRLMBER.IHIDNUM IS '주민등록번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.MBER_NM IS '회원명'; 
COMMENT ON COLUMN LETTNGNRLMBER.ZIP IS '우편번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.ADRES IS '주소'; 
COMMENT ON COLUMN LETTNGNRLMBER.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.MBER_STTUS IS '회원상태'; 
COMMENT ON COLUMN LETTNGNRLMBER.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN LETTNGNRLMBER.END_TELNO IS '끝전화번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN LETTNGNRLMBER.MBER_FXNUM IS '회원팩스번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.MBER_EMAIL_ADRES IS '회원이메일주소'; 
COMMENT ON COLUMN LETTNGNRLMBER.MIDDLE_TELNO IS '중간전화번호'; 
COMMENT ON COLUMN LETTNGNRLMBER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN LETTNGNRLMBER.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN LETTNGNRLMBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_LOGIN_LOG (접속로그)
CREATE TABLE IF NOT EXISTS LETTNLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(20) DEFAULT NULL,
  CONECT_IP varchar(23) DEFAULT NULL,
  CONECT_MTHD char(4) DEFAULT NULL,
  ERROR_OCCRRNC_AT char(1) DEFAULT NULL,
  ERROR_CODE char(3) DEFAULT NULL,
  CREAT_DT timestamp DEFAULT NULL,
  PRIMARY KEY (LOG_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNLOGINLOG IS '접속로그'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNLOGINLOG.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN LETTNLOGINLOG.CONECT_ID IS '접속ID'; 
COMMENT ON COLUMN LETTNLOGINLOG.CONECT_IP IS '접속IP'; 
COMMENT ON COLUMN LETTNLOGINLOG.CONECT_MTHD IS '접속방식'; 
COMMENT ON COLUMN LETTNLOGINLOG.ERROR_OCCRRNC_AT IS '오류발생여부'; 
COMMENT ON COLUMN LETTNLOGINLOG.ERROR_CODE IS '오류코드'; 
COMMENT ON COLUMN LETTNLOGINLOG.CREAT_DT IS '생성일시'; 

-- LET_TN_LOGIN_POLICY (로그인정책)
CREATE TABLE IF NOT EXISTS LETTNLOGINPOLICY (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  IP_INFO varchar(23) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMTT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNLOGINPOLICY IS '로그인정책'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNLOGINPOLICY.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LETTNLOGINPOLICY.IP_INFO IS 'IP정보'; 
COMMENT ON COLUMN LETTNLOGINPOLICY.DPLCT_PERM_AT IS '중복허용여부'; 
COMMENT ON COLUMN LETTNLOGINPOLICY.LMTT_AT IS '제한여부'; 
COMMENT ON COLUMN LETTNLOGINPOLICY.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNLOGINPOLICY.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNLOGINPOLICY.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LETTNLOGINPOLICY.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_PROGRM_LIST (프로그램목록)
CREATE TABLE IF NOT EXISTS LETTNPROGRMLIST (
  PROGRM_FILE_NM varchar(60) NOT NULL DEFAULT '',
  PROGRM_STRE_PATH varchar(100) NOT NULL,
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL,
  PROGRM_DC varchar(200) DEFAULT NULL,
  URL varchar(100) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNPROGRMLIST IS '프로그램목록'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_FILE_NM IS '프로그램파일명'; 
COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_STRE_PATH IS '프로그램저장경로'; 
COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_KOREAN_NM IS '프로그램한글명'; 
COMMENT ON COLUMN LETTNPROGRMLIST.PROGRM_DC IS '프로그램설명'; 
COMMENT ON COLUMN LETTNPROGRMLIST.URL IS 'URL'; 

-- LET_TN_MENU_INFO (메뉴정보)
CREATE TABLE IF NOT EXISTS LETTNMENUINFO (
  MENU_NM varchar(60) NOT NULL,
  PROGRM_FILE_NM varchar(60) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0) DEFAULT NULL,
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC varchar(250) DEFAULT NULL,
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL,
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL,
  PRIMARY KEY (MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES LETTNPROGRMLIST (PROGRM_FILE_NM) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnmenuinfo_progrm_file_nm ON LETTNMENUINFO (PROGRM_FILE_NM);
CREATE INDEX IF NOT EXISTS idx_lettnmenuinfo_upper_menu_no ON LETTNMENUINFO (UPPER_MENU_NO);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNMENUINFO IS '메뉴정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNMENUINFO.MENU_NO IS '메뉴번호'; 
COMMENT ON COLUMN LETTNMENUINFO.UPPER_MENU_NO IS '상위메뉴번호'; 
COMMENT ON COLUMN LETTNMENUINFO.MENU_NM IS '메뉴명'; 
COMMENT ON COLUMN LETTNMENUINFO.PROGRM_FILE_NM IS '프로그램파일명'; 
COMMENT ON COLUMN LETTNMENUINFO.MENU_ORDR IS '메뉴순서'; 
COMMENT ON COLUMN LETTNMENUINFO.MENU_DC IS '메뉴설명'; 
COMMENT ON COLUMN LETTNMENUINFO.RELATE_IMAGE_PATH IS '관계이미지경로'; 
COMMENT ON COLUMN LETTNMENUINFO.RELATE_IMAGE_NM IS '관계이미지명'; 

-- LET_TN_MENU_CREAT_DTLS (메뉴생성내역)
CREATE TABLE IF NOT EXISTS LETTNMENUCREATDTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL,
  PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnmenucreatdtls_mapng ON LETTNMENUCREATDTLS (MAPNG_CREAT_ID);
CREATE INDEX IF NOT EXISTS idx_lettnmenucreatdtls_author ON LETTNMENUCREATDTLS (AUTHOR_CODE);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNMENUCREATDTLS IS '메뉴생성내역'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNMENUCREATDTLS.MENU_NO IS '메뉴번호'; 
COMMENT ON COLUMN LETTNMENUCREATDTLS.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN LETTNMENUCREATDTLS.MAPNG_CREAT_ID IS '매핑생성ID'; 

-- LET_TN_USER_ABSNCE (사용자부재)
CREATE TABLE IF NOT EXISTS LETTNUSERABSNCE (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNUSERABSNCE IS '사용자부재'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNUSERABSNCE.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN LETTNUSERABSNCE.USER_ABSNCE_AT IS '사용자부재여부'; 
COMMENT ON COLUMN LETTNUSERABSNCE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNUSERABSNCE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNUSERABSNCE.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LETTNUSERABSNCE.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TS_SYS_LOG_SUMMARY (시스템로그요약)
CREATE TABLE IF NOT EXISTS LETTSSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(255) NOT NULL,
  METHOD_NM varchar(60) NOT NULL,
  CREAT_CO numeric(10,0) DEFAULT NULL,
  UPDT_CO numeric(10,0) DEFAULT NULL,
  RDCNT numeric(10,0) DEFAULT NULL,
  DELETE_CO numeric(10,0) DEFAULT NULL,
  OUTPT_CO numeric(10,0) DEFAULT NULL,
  ERROR_CO numeric(10,0) DEFAULT NULL,
  PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
);
-- 테이블에 대한 설명
COMMENT ON TABLE LETTSSYSLOGSUMMARY IS '시스템로그요약';
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.OCCRRNC_DE IS '발생일'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.SRVC_NM IS '서비스명'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.METHOD_NM IS '메서드명'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.CREAT_CO IS '생성수'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.UPDT_CO IS '수정수'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.RDCNT IS '조회수'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.DELETE_CO IS '삭제수'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.OUTPT_CO IS '출력수'; 
COMMENT ON COLUMN LETTSSYSLOGSUMMARY.ERROR_CO IS '오류수'; 

-- View COM_VN_USER_MASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER (
  ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID
) AS
        SELECT ESNTL_ID, MBER_ID AS USER_ID,PASSWORD,MBER_NM AS USER_NM,ZIP AS USER_ZIP,ADRES AS USER_ADRES,MBER_EMAIL_ADRES AS USER_EMAIL,' ' AS GROUP_ID,'GNR' AS USER_SE, ' ' AS ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID AS USER_ID,PASSWORD,USER_NM,ZIP AS USER_ZIP,HOUSE_ADRES AS USER_ADRES,EMAIL_ADRES AS USER_EMAIL,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID AS USER_ID,ENTRPRS_MBER_PASSWORD AS PASSWORD,CMPNY_NM AS USER_NM,ZIP AS USER_ZIP,ADRES AS USER_ADRES,APPLCNT_EMAIL_ADRES AS USER_EMAIL,' ' AS GROUP_ID,'ENT' AS USER_SE, ' ' AS ORGNZT_ID
        FROM LETTNENTRPRSMBER
;


